"""Add User table

Revision ID: 1ae011a06e02
Revises: cd245ddd036b
Create Date: 2025-12-31 15:45:07.645386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae011a06e02'
down_revision: Union[str, Sequence[str], None] = 'cd245ddd036b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # Skip dropping apscheduler tables/indexes - managed by APScheduler itself
    # op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    op.drop_column('bot_settings', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_settings', sa.Column('language', sa.VARCHAR(), nullable=False))
    # Skip recreating apscheduler tables/indexes on downgrade - managed by APScheduler itself
    # op.create_table('apscheduler_jobs', ...)
    # op.create_index(...)
    op.drop_table('users')
    # ### end Alembic commands ###
