"""Add AlertStorage and language setting

Revision ID: cd245ddd036b
Revises: 0aa5319795f4
Create Date: 2025-12-31 14:08:15.712495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd245ddd036b'
down_revision: Union[str, Sequence[str], None] = '0aa5319795f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_storage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip dropping apscheduler tables/indexes - managed by APScheduler itself
    # op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    op.add_column('bot_settings', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_settings', 'language')
    # Skip recreating apscheduler tables/indexes on downgrade - managed by APScheduler itself
    # op.create_table('apscheduler_jobs',...)
    # op.create_index(...)
    op.drop_table('alert_storage')
    # ### end Alembic commands ###
