# Simple localization dictionary
TEXTS = {
    'en': {
        'start_welcome': "Welcome to Mollyy Posting Bot! 🚀\nSelect an option from the menu below.",
        'channels_list': "Here are your connected channels:",
        'add_channel_prompt': "Please forward a message from the channel you want to add.\nMake sure I am an admin there first!",
        'channel_added': "✅ Channel '{title}' added successfully!",
        'channel_exists': "Channel already added!",
        'not_admin': "I am not an admin in that channel. Please promote me and try again.",
        'select_channel': "Select a channel to post to:",
        'no_channels': "No channels connected. Please add a channel first.",
        'send_content': "✅ Channel selected.\n\nNow send me the content for the post.\n(Text, Photo, Video, Document, or Album)",
        'content_received': "Content received!",
        'unsupported_type': "Unsupported content type.",
        'send_btn_label': "Send the **Label** for the button:",
        'send_btn_url': "Now send the **URL** (link):",
        'send_alert_text': "Now send the text for the **Alert**:",
        'send_webapp_url': "Now send the **WebApp URL**:",
        'btn_added': "✅ Button added.",
        'post_published': "✅ Published successfully!",
        'post_scheduled': "✅ Post scheduled for {date}!",
        'schedule_prompt': "Enter date and time for publication.\nFormat: `DD.MM.YYYY HH:MM` (e.g. 31.12.2025 23:59)",
        'invalid_date': "Invalid format. Please use `DD.MM.YYYY HH:MM`",
        'btn_translate_prompt': "Enter language code (e.g. 'en' for English, 'es' for Spanish) or just 'en':",
        'translation_added': "✅ Translation added.",
        'no_text_translate': "No text found to translate!",
        'settings_menu': "⚙️ **Admin Settings**\n\nChoose an option:",
        'edit_denied_text': "Please send the new text for non-admin users:",
        'denied_updated': "✅ 'Access Denied' text updated!",
        'no_scheduled': "No scheduled posts found.",
        'language_selected': "✅ Language switched to English.",
        'main_menu_create': "📝 Create Post",
        'main_menu_channels': "📢 Channels",
        'main_menu_settings': "⚙️ Settings",
    },
    'ru': {
        'start_welcome': "Добро пожаловать в Mollyy Posting Bot! 🚀\nВыберите опцию в меню ниже.",
        'channels_list': "Вот ваши подключенные каналы:",
        'add_channel_prompt': "Пожалуйста, перешлите сообщение из канала, который хотите добавить.\nУбедитесь, что я там админ!",
        'channel_added': "✅ Канал '{title}' успешно добавлен!",
        'channel_exists': "Канал уже добавлен!",
        'not_admin': "Я не админ в этом канале. Пожалуйста, назначьте меня и попробуйте снова.",
        'select_channel': "Выберите канал для публикации:",
        'no_channels': "Нет подключенных каналов. Сначала добавьте канал.",
        'send_content': "✅ Канал выбран.\n\nТеперь отправьте контент для поста.\n(Текст, Фото, Видео, Документ или Альбом)",
        'content_received': "Контент получен!",
        'unsupported_type': "Неподдерживаемый тип контента.",
        'send_btn_label': "Отправьте **Название** кнопки:",
        'send_btn_url': "Теперь отправьте **URL** (ссылку):",
        'send_alert_text': "Теперь отправьте текст для **Alert** (всплывающего окна):",
        'send_webapp_url': "Теперь отправьте **WebApp URL**:",
        'btn_added': "✅ Кнопка добавлена.",
        'post_published': "✅ Успешно опубликовано!",
        'post_scheduled': "✅ Пост отложен на {date}!",
        'schedule_prompt': "Введите дату и время публикации.\nФормат: `DD.MM.YYYY HH:MM` (например 31.12.2025 23:59)",
        'invalid_date': "Неверный формат. Используйте `DD.MM.YYYY HH:MM`",
        'btn_translate_prompt': "Введите код языка (например 'en' для английского) или просто 'en':",
        'translation_added': "✅ Перевод добавлен.",
        'no_text_translate': "Текст для перевода не найден!",
        'settings_menu': "⚙️ **Настройки Админа**\n\nВыберите опцию:",
        'edit_denied_text': "Отправьте новый текст для пользователей без прав админа:",
        'denied_updated': "✅ Текст 'Доступ запрещен' обновлен!",
        'no_scheduled': "Нет запланированных постов.",
        'language_selected': "✅ Язык переключен на Русский.",
        'main_menu_create': "📝 Создать пост",
        'main_menu_channels': "📢 Каналы",
        'main_menu_settings': "⚙️ Настройки",
    }
}

async def get_text(key: str, lang: str = 'ru', **kwargs) -> str:
    # Fallback to English if key missing in lang, or ru if totally missing
    lang_dict = TEXTS.get(lang, TEXTS['ru'])
    text = lang_dict.get(key, TEXTS['en'].get(key, key))
    return text.format(**kwargs)